site_name: "Ponderada de programaÃ§Ã£o semana 9 - M10"
theme:
  name: "material"
nav:
  - Passo a passo ğŸ£: passo.md
  - O que Ã© terraform ğŸ¤”: index.md
  - ConfiguraÃ§Ã£o na sua maquina ğŸ¤–: config.md
  - Terraform ğŸŸª: terraform.md
  - Logs ğŸ“—: logs.md
